version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: api
    volumes:
      - ./src:/var/www
    working_dir: /var/www
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: nginx-server
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: 172.17.0.1
      PMA_ABSOLUTE_URI: http://localhost:8080/
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    networks:
      - laravel

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: si-imah
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "80:80"
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
